# Generated by Django 5.2.2 on 2025-06-06 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curral', '0001_initial'),
        ('lote', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('idmovimentacao', models.AutoField(help_text='Identificador único da movimentação.', primary_key=True, serialize=False)),
                ('data_movimentacao', models.DateField(help_text='Data em que a movimentação ocorreu.')),
            ],
            options={
                'db_table': 'movimentacao',
            },
        ),
        migrations.CreateModel(
            name='StatusMovimentacao',
            fields=[
                ('idstatus_movimentacao', models.AutoField(help_text='Identificador único do status de movimentação.', primary_key=True, serialize=False)),
                ('nome_status', models.CharField(help_text="Descrição do status da movimentação (por exemplo: 'Em trânsito', 'Concluída').", max_length=45)),
            ],
            options={
                'db_table': 'status_movimentacao',
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoLoteDestino',
            fields=[
                ('idmovimentacao_lote_destino', models.AutoField(help_text='Identificador único do registro de destino de lote em movimentação.', primary_key=True, serialize=False)),
                ('curral', models.ForeignKey(help_text='Curral de destino da movimentação.', on_delete=django.db.models.deletion.PROTECT, related_name='movdestino_curral', to='curral.curral')),
                ('lote', models.ForeignKey(help_text='Lote de destino da movimentação.', on_delete=django.db.models.deletion.PROTECT, related_name='movdestino_lote', to='lote.lote')),
                ('movimentacao', models.ForeignKey(help_text='Movimentação associada ao destino.', on_delete=django.db.models.deletion.PROTECT, related_name='movdestino_mov', to='movimentacao.movimentacao')),
            ],
            options={
                'db_table': 'movimentacao_lote_destino',
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoLoteOrigem',
            fields=[
                ('idmovimentacao_lote_origem', models.AutoField(help_text='Identificador único do registro de origem de lote em movimentação.', primary_key=True, serialize=False)),
                ('curral', models.ForeignKey(help_text='Curral de origem da movimentação.', on_delete=django.db.models.deletion.PROTECT, related_name='movorigem_curral', to='curral.curral')),
                ('lote', models.ForeignKey(help_text='Lote de origem da movimentação.', on_delete=django.db.models.deletion.PROTECT, related_name='movorigem_lote', to='lote.lote')),
                ('movimentacao', models.ForeignKey(help_text='Movimentação associada à origem.', on_delete=django.db.models.deletion.PROTECT, related_name='movorigem_mov', to='movimentacao.movimentacao')),
            ],
            options={
                'db_table': 'movimentacao_lote_origem',
            },
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='status',
            field=models.ForeignKey(help_text='Status atual da movimentação.', on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='movimentacao.statusmovimentacao'),
        ),
    ]
