# Generated by Django 5.2.2 on 2025-06-10 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimentacaolotedestino',
            name='curral',
        ),
        migrations.RemoveField(
            model_name='movimentacaoloteorigem',
            name='curral',
        ),
    ]
