# Generated by Django 5.2.2 on 2025-06-10 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curral', '0001_initial'),
        ('movimentacao', '0002_remove_movimentacaolotedestino_curral_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaolotedestino',
            name='curral',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='curral.curral'),
            preserve_default=False,
        ),
    ]
