# Generated by Django 5.2.2 on 2025-06-10 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lote', '0001_initial'),
        ('movimentacao', '0003_movimentacaolotedestino_curral'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimentacao',
            name='status',
        ),
        migrations.RemoveField(
            model_name='movimentacao',
            name='idmovimentacao',
        ),
        migrations.RemoveField(
            model_name='movimentacaolotedestino',
            name='idmovimentacao_lote_destino',
        ),
        migrations.RemoveField(
            model_name='movimentacaoloteorigem',
            name='idmovimentacao_lote_origem',
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='movimentacaolotedestino',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='movimentacaoloteorigem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='data_movimentacao',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='movimentacaolotedestino',
            name='lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lote.lote'),
        ),
        migrations.AlterField(
            model_name='movimentacaolotedestino',
            name='movimentacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movimentacao.movimentacao'),
        ),
        migrations.AlterField(
            model_name='movimentacaoloteorigem',
            name='lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lote.lote'),
        ),
        migrations.AlterField(
            model_name='movimentacaoloteorigem',
            name='movimentacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movimentacao.movimentacao'),
        ),
        migrations.AlterModelTable(
            name='movimentacao',
            table=None,
        ),
        migrations.AlterModelTable(
            name='movimentacaolotedestino',
            table=None,
        ),
        migrations.AlterModelTable(
            name='movimentacaoloteorigem',
            table=None,
        ),
        migrations.DeleteModel(
            name='StatusMovimentacao',
        ),
    ]
