# Generated by Django 5.2.2 on 2025-06-10 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lote', '0001_initial'),
        ('movimentacao', '0004_remove_movimentacao_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusMovimentacao',
            fields=[
                ('idstatus_movimentacao', models.AutoField(help_text='Identificador único do status de movimentação.', primary_key=True, serialize=False)),
                ('nome_status', models.CharField(help_text="Descrição do status da movimentação (por exemplo: 'Em trânsito', 'Concluída').", max_length=45)),
            ],
            options={
                'db_table': 'status_movimentacao',
            },
        ),
        migrations.RemoveField(
            model_name='movimentacao',
            name='id',
        ),
        migrations.RemoveField(
            model_name='movimentacaolotedestino',
            name='id',
        ),
        migrations.RemoveField(
            model_name='movimentacaoloteorigem',
            name='id',
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='idmovimentacao',
            field=models.AutoField(help_text='Identificador único da movimentação.', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='movimentacaolotedestino',
            name='idmovimentacao_lote_destino',
            field=models.AutoField(help_text='Identificador único do registro de destino de lote em movimentação.', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='movimentacaoloteorigem',
            name='idmovimentacao_lote_origem',
            field=models.AutoField(help_text='Identificador único do registro de origem de lote em movimentação.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='data_movimentacao',
            field=models.DateField(help_text='Data em que a movimentação ocorreu.'),
        ),
        migrations.AlterField(
            model_name='movimentacaolotedestino',
            name='lote',
            field=models.ForeignKey(help_text='Lote de destino da movimentação.', on_delete=django.db.models.deletion.PROTECT, related_name='movdestino_lote', to='lote.lote'),
        ),
        migrations.AlterField(
            model_name='movimentacaolotedestino',
            name='movimentacao',
            field=models.ForeignKey(help_text='Movimentação associada ao destino.', on_delete=django.db.models.deletion.PROTECT, related_name='movdestino_mov', to='movimentacao.movimentacao'),
        ),
        migrations.AlterField(
            model_name='movimentacaoloteorigem',
            name='lote',
            field=models.ForeignKey(help_text='Lote de origem da movimentação.', on_delete=django.db.models.deletion.PROTECT, related_name='movorigem_lote', to='lote.lote'),
        ),
        migrations.AlterField(
            model_name='movimentacaoloteorigem',
            name='movimentacao',
            field=models.ForeignKey(help_text='Movimentação associada à origem.', on_delete=django.db.models.deletion.PROTECT, related_name='movorigem_mov', to='movimentacao.movimentacao'),
        ),
        migrations.AlterModelTable(
            name='movimentacao',
            table='movimentacao',
        ),
        migrations.AlterModelTable(
            name='movimentacaolotedestino',
            table='movimentacao_lote_destino',
        ),
        migrations.AlterModelTable(
            name='movimentacaoloteorigem',
            table='movimentacao_lote_origem',
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='status',
            field=models.ForeignKey(default=1, help_text='Status atual da movimentação.', on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='movimentacao.statusmovimentacao'),
            preserve_default=False,
        ),
    ]
