# Generated by Django 5.2.2 on 2025-06-10 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curral', '0001_initial'),
        ('lote', '0001_initial'),
        ('movimentacao', '0005_statusmovimentacao_remove_movimentacao_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimentacaoloteorigem',
            name='lote',
        ),
        migrations.RemoveField(
            model_name='movimentacaoloteorigem',
            name='movimentacao',
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='curral_destino',
            field=models.ForeignKey(default=1, help_text='Curral para onde os animais estão indo.', on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_para_destino_curral', to='curral.curral'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='curral_origem',
            field=models.ForeignKey(default=1, help_text='Curral de onde os animais estão saindo.', on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_de_origem_curral', to='curral.curral'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='lote_destino',
            field=models.ForeignKey(default=1, help_text='Lote para onde os animais estão indo.', on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_para_destino', to='lote.lote'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='lote_origem',
            field=models.ForeignKey(default=1, help_text='Lote de onde os animais estão saindo.', on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_de_origem', to='lote.lote'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='data_movimentacao',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='idmovimentacao',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movimentacao.statusmovimentacao'),
        ),
        migrations.AlterField(
            model_name='statusmovimentacao',
            name='idstatus_movimentacao',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='statusmovimentacao',
            name='nome_status',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterModelTable(
            name='movimentacao',
            table=None,
        ),
        migrations.AlterModelTable(
            name='statusmovimentacao',
            table=None,
        ),
        migrations.DeleteModel(
            name='MovimentacaoLoteDestino',
        ),
        migrations.DeleteModel(
            name='MovimentacaoLoteOrigem',
        ),
    ]
