# Generated by Django 5.2.2 on 2025-06-10 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curral', '0001_initial'),
        ('lote', '0001_initial'),
        ('movimentacao', '0006_remove_movimentacaoloteorigem_lote_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimentacao',
            name='curral_origem',
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='curral_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_curral_destino', to='curral.curral'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='lote_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_destino', to='lote.lote'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='lote_origem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_origem', to='lote.lote'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='movimentacao.statusmovimentacao'),
        ),
        migrations.AlterModelTable(
            name='movimentacao',
            table='movimentacao',
        ),
        migrations.AlterModelTable(
            name='statusmovimentacao',
            table='status_movimentacao',
        ),
    ]
