# Generated by Django 5.2.2 on 2025-06-06 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtocoloSanitario',
            fields=[
                ('idprotocolo_sanitario', models.AutoField(help_text='Identificador único do protocolo sanitário.', primary_key=True, serialize=False)),
                ('nome_protocolo', models.CharField(help_text='Nome do protocolo sanitário.', max_length=45)),
                ('motivo_protocolo', models.CharField(help_text='Motivo ou objetivo do protocolo sanitário.', max_length=110)),
                ('quantidade', models.IntegerField(help_text='Quantidade de animais abrangidos pelo protocolo (ou outra métrica relevante).')),
                ('responsavel_tecnico', models.ForeignKey(help_text='Técnico responsável pela formulação ou execução do protocolo.', on_delete=django.db.models.deletion.PROTECT, related_name='protocolos_por_tecnico', to='medicamento.responsaveltecnico')),
            ],
            options={
                'db_table': 'protocolo_sanitario',
            },
        ),
        migrations.CreateModel(
            name='ProtocoloMedicamento',
            fields=[
                ('idprotocolo_medicamento', models.AutoField(help_text='Identificador único da relação entre protocolo sanitário e medicamento.', primary_key=True, serialize=False)),
                ('medicamento', models.ForeignKey(help_text='Medicamento associado ao protocolo.', on_delete=django.db.models.deletion.PROTECT, related_name='protocolos_medicamento', to='medicamento.medicamento')),
                ('protocolo_sanitario', models.ForeignKey(help_text='Protocolo sanitário ao qual o medicamento pertence.', on_delete=django.db.models.deletion.PROTECT, related_name='protocolos_por_sanitario', to='protocolo.protocolosanitario')),
            ],
            options={
                'db_table': 'protocolo_medicamento',
            },
        ),
    ]
