# Generated by Django 5.2.2 on 2025-06-06 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamento', '0001_initial'),
        ('protocolo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protocolosanitario',
            name='quantidade',
        ),
        migrations.AddField(
            model_name='protocolomedicamento',
            name='dose_protocolo',
            field=models.IntegerField(default=1, help_text='Quantidade de ml.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='protocolosanitario',
            name='medicamentos',
            field=models.ManyToManyField(related_name='protocolos', through='protocolo.ProtocoloMedicamento', to='medicamento.medicamento'),
        ),
    ]
