# Generated by Django 5.2.2 on 2025-06-09 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolo', '0002_remove_protocolosanitario_quantidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocolomedicamento',
            name='protocolo_sanitario',
            field=models.ForeignKey(help_text='Protocolo sanitário ao qual o medicamento pertence.', on_delete=django.db.models.deletion.CASCADE, related_name='protocolos_por_sanitario', to='protocolo.protocolosanitario'),
        ),
    ]
