# Generated by Django 5.2.2 on 2025-06-06 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCurral',
            fields=[
                ('idTipo_curral', models.AutoField(help_text='Identificador único do tipo de curral.', primary_key=True, serialize=False)),
                ('nome_tipo_curral', models.CharField(help_text="Descrição do tipo de curral (por exemplo: 'Confinamento', 'Pasto').", max_length=45)),
            ],
            options={
                'db_table': 'Tipo_curral',
            },
        ),
        migrations.CreateModel(
            name='Curral',
            fields=[
                ('idCurral', models.AutoField(help_text='Identificador único do curral.', primary_key=True, serialize=False)),
                ('nome_curral', models.CharField(help_text='Nome ou código do curral.', max_length=70)),
                ('peso_min', models.DecimalField(decimal_places=2, help_text='Peso mínimo suportado no curral (em kg).', max_digits=6)),
                ('peso_max', models.DecimalField(decimal_places=2, help_text='Peso máximo suportado no curral (em kg).', max_digits=6)),
                ('area_m2', models.DecimalField(decimal_places=2, help_text='Área total do curral em metros quadrados.', max_digits=6)),
                ('area_coche', models.DecimalField(decimal_places=2, help_text='Área destinada à cocheira (descanso) dentro do curral, em metros quadrados.', max_digits=6)),
                ('ativo', models.BooleanField(default=True, help_text='Indica se o curral está ativo (True) ou inativo (False).')),
                ('tipo_curral', models.ForeignKey(help_text='Referência ao tipo de curral.', on_delete=django.db.models.deletion.PROTECT, related_name='currais', to='curral.tipocurral')),
            ],
            options={
                'db_table': 'Curral',
            },
        ),
    ]
