# Generated by Django 5.2.2 on 2025-06-25 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curral', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curral',
            old_name='area_coche',
            new_name='area_cocho',
        ),
    ]
