# Generated by Django 5.2.2 on 2025-06-27 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamentoaplicado',
            name='medicamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicamento.medicamento'),
        ),
    ]
