# Generated by Django 4.2.20 on 2025-06-25 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lote', '0001_initial'),
        ('boi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boi',
            name='brinco',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='boi',
            name='chip',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='boi',
            name='data_entrada',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='boi',
            name='data_morte',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boi',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boi',
            name='data_saida',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boi',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bois_por_fornecedor', to='boi.fornecedor'),
        ),
        migrations.AlterField(
            model_name='boi',
            name='idboi',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='boi',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bois_por_lote', to='lote.lote'),
        ),
        migrations.AlterField(
            model_name='boi',
            name='motivo_morte',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='boi',
            name='necropsia',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='boi',
            name='peso_entrada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='boi',
            name='peso_saida',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='boi',
            name='raca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bois_por_raca', to='boi.raca'),
        ),
        migrations.AlterField(
            model_name='boi',
            name='sexo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bois_por_sexo', to='boi.sexo'),
        ),
        migrations.AlterField(
            model_name='boi',
            name='status_boi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bois_por_status', to='boi.statusboi'),
        ),
        migrations.AlterField(
            model_name='pesomovimentacao',
            name='boi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pesagens', to='boi.boi'),
        ),
        migrations.AlterField(
            model_name='pesomovimentacao',
            name='data_movimentacao',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pesomovimentacao',
            name='id_peso_movimentacao',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pesomovimentacao',
            name='peso_movimentacao',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='pesoprojetado',
            name='boi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projecoes_peso', to='boi.boi'),
        ),
        migrations.AlterField(
            model_name='pesoprojetado',
            name='data_projetado',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pesoprojetado',
            name='peso_projetado',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='statusboi',
            name='nome_status',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Morto', 'Morto'), ('Vendido', 'Vendido')], max_length=10),
        ),
    ]
