# Generated by Django 5.2.2 on 2025-06-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boi', '0002_alter_boi_brinco_alter_boi_chip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boi',
            name='brinco',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='boi',
            name='chip',
            field=models.CharField(default=12, max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
