# Generated by Django 5.2.2 on 2025-06-06 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manejo', '0002_alter_boimanejo_protocolo_sanitario'),
        ('protocolo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boimanejo',
            name='protocolo_sanitario',
            field=models.ForeignKey(blank=True, help_text='Protocolo sanitário utilizado no manejo.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bois_protocolo', to='protocolo.protocolosanitario'),
        ),
    ]
