# Generated by Django 5.2.2 on 2025-06-09 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boi', '0001_initial'),
        ('lote', '0001_initial'),
        ('manejo', '0003_alter_boimanejo_protocolo_sanitario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boimanejo',
            name='idboi_manejo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='manejo',
            name='idManejo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='statusmanejo',
            name='idstatus_manejo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tipomanejo',
            name='idtipo_manejo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='manejo',
            table='manejo',
        ),
        migrations.CreateModel(
            name='ParametroManejo',
            fields=[
                ('idparametro_manejo', models.AutoField(primary_key=True, serialize=False)),
                ('peso_inicial', models.DecimalField(decimal_places=2, help_text='Peso inicial dos animais do lote.', max_digits=5)),
                ('peso_final', models.DecimalField(decimal_places=2, help_text='Peso final dos animais do lote.', max_digits=5)),
                ('lote', models.ForeignKey(help_text='Lote envolvido no manejo.', on_delete=django.db.models.deletion.PROTECT, to='lote.lote')),
                ('manejo', models.ForeignKey(help_text='Manejo ao qual este parâmetro pertence.', on_delete=django.db.models.deletion.CASCADE, related_name='parametros_manejo', to='manejo.manejo')),
                ('raca', models.ForeignKey(help_text='Raça dos animais no lote.', on_delete=django.db.models.deletion.PROTECT, to='boi.raca')),
            ],
            options={
                'db_table': 'parametro_manejo',
            },
        ),
    ]
