# Generated by Django 5.2.2 on 2025-06-16 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manejo', '0004_alter_boimanejo_idboi_manejo_alter_manejo_idmanejo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipomanejo',
            name='nome_tipo_manejo',
            field=models.CharField(help_text="Descrição do tipo de manejo (por exemplo: 'Pesagem', 'Vacinação').", max_length=20),
        ),
    ]
